---
- name: Vbox Role | Install Virtualbox
  apt:
    name: virtualbox
    state: present

- name: Vbox Role | Create Directory for ISOs
  file:
    path: "{{ vbox_dir_isos }}"
    state: directory
    owner: "{{ vbox_user }}"
    group: "{{ vbox_user }}"
    mode: 075

- name: VBox Role | Create Directory for VMs
  file:
    path: "{{ vbox_dir_vms }}"
    state: directory
    owner: "{{ vbox_user }}"
    group: "{{ vbox_user }}"
    mode: 0755

- name: VBox Role | Download ISO Images
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.path }}"
  with_items:
    - "{{ vbox_images_isos }}"

- name: VBox Role | Copy custom images
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ vbox_custom_isos }}"
  when: vbox_custom_isos

- name: "VBox | Create VMs"
  vars:
    name: "{{ item.name | default('VM_Default') }}"
    os_type: "{{ item.os_type | default('Ubuntu_64') }}"
    ram: "{{ item.ram | default(2048) }}"
    cpus: "{{ item.cpus | default(2) }}"
    disk_size: "{{ item.disk_size | default(20480) }}"
    disk_path: "{{ item.disk_path | default('/home/{{ vbox_user }}/.VMsDisks/VM_Default') }}"
    disk_format: "{{ item.disk_format | default('VDI') }}"
    net_type: "{{ item.net_type | default('bridged') }}"
    bridgeadapter: "{{ item.bridgeadapter | default('enp0s3') }}"
    vram: "{{ item.vram | default(128) }}"
    iso_path: "{{ item.iso_path }}" #required
  shell: |
    vboxmanage createvm --name "{{ name }}" --ostype "{{ os_type }}" --register
    vboxmanage modifyvm "{{ name }}" \
    --memory "{{ ram }}" \
    --cpus "{{ cpus }}" \
    --nic1 "{{ net_type }}" \
    --bridgeadapter1 "{{ bridgeadapter }}" \
    --vram "{{ vram }}" \
    --draganddrop bidirectional \
    --clipboard bidirectional \
    --boot1 dvd \
    --boot2 disk \
    --boot3 none \
    --boot4 none
    vboxmanage createmedium disk --filename "{{ disk_path }}" --size "{{ disk_size }}" --format "{{ disk_format }}" --variant Standard
    vboxmanage storagectl "{{ name }}" --name "SATA Controller" --add sata --bootable on
    vboxmanage storagectl "{{ name }}" --name "IDE Controller" --add ide --bootable on
    vboxmanage storageattach "{{ name }}" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "{{ disk_path }}.vdi"
    vboxmanage storageattach "{{ name }}" --storagectl "IDE Controller" --port 0 --device 0 --type dvddrive --medium "{{ iso_path }}"
  become_user: "{{ vbox_user }}"
  loop: "{{ vbox_vms_options }}"
  when: vbox_vms_options is defined

